### ISSUE TITLE
Force region/flag from text

### ISSUE THREAD

**Issue by andrii-lisovskiy** [marmelroy/PhoneNumberKit#504] opened 2022-01-17 15:33 UTC
When I am setting text to textField it takes current region, and shows its flag.
It changes only when I am editing text.
So, how to force region and flag changing when setting text for PhoneNumberTextField?

**Comment by AlessandroMulloni** [comment] 2022-03-09 09:08
Duplicate of https://github.com/marmelroy/PhoneNumberKit/issues/496

**Comment by bguidolim** [comment] 2022-04-21 08:38
Closed with #512

**Closed by bguidolim** 2022-04-21 08:38 UTC
