### ISSUE TITLE
Xcode 12: 'PhoneNumberKit' has different definitions in different modules; first difference is definition in module 'PhoneNumberKit.Swift' found method with no designater initializer

### ISSUE THREAD

**Issue by christiygag** [marmelroy/PhoneNumberKit#406] opened 2020-09-18 16:10 UTC
Getting the below error when I am trying to build the code using Xcode 12.

> 'PhoneNumberKit' has different definitions in different modules; first difference is definition in module 'PhoneNumberKit.Swift' found method with no designater initializer

<img width="915" alt="Screen Shot 2020-09-18 at 8 05 55 PM" src="https://user-images.githubusercontent.com/20677361/93620357-eb166b80-f9ea-11ea-985e-bf4dd7f947cb.png">

**Comment by fahedalahmad** [comment] 2020-09-20 13:03
Any update?

**Comment by marmelroy** [comment] 2020-09-21 08:19
Is this still an issue with the new release? Any steps to reproduce? How are you integrating PhoneNumberKit?

@christiygag @fahedalahmad

**Comment by fahedalahmad** [comment] 2020-09-21 10:17
It has conflict with the blow pod:
https://github.com/checkout/frames-ios , version: 3.0.5

PhoneNumberKit version: 3.2.0

Using Xcode 12.
Build system: Use Shared Setting

**Comment by azibas-tg** [comment] 2020-09-22 11:23
Same issue on Xcode 12, with same pods:

PhoneNumberKit version: 3.2.0
https://github.com/checkout/frames-ios , version: 3.0.5

**Comment by marmelroy** [comment] 2020-09-25 11:44
There's not a lot we can do about this. The issue is on the Frames side because they are including a checked-in version of PhoneNumberKit. They should update it.

**Comment by marmelroy** [comment] 2020-09-25 11:44
Closing for now.

**Closed by marmelroy** 2020-09-25 11:44 UTC
