### ISSUE TITLE
parseMultiple EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by nrako** [marmelroy/PhoneNumberKit#29] opened 2016-03-02 11:24 UTC
When using `PhoneNumberKit().parseMultiple()` from time to time I have the following issue:

![screen shot 2016-03-02 at 12 10 09](https://cloud.githubusercontent.com/assets/425397/13458902/681896b0-e070-11e5-8859-70ed4c9002ef.png)

![screen shot 2016-03-02 at 12 12 13](https://cloud.githubusercontent.com/assets/425397/13458911/6fcd0544-e070-11e5-8d8f-607e2f8851d1.png)

I didn't really took a look into this more thoroughly, I just want to raise this issue to see if it's already under investigation.

By the way, love this lib! `parseMultiple()` is more than 2x more performant than our previous implementation :rocket:

**Comment by marmelroy** [comment] 2016-03-02 11:26
Thanks @nrako. Didn't know about this issue. Will investigate...

**Comment by nrako** [comment] 2016-03-04 15:50
Thanks @marmelroy 

I also have an SIGABRT error sometimes but I have the feeling it's related so I'm reporting it here.

![screen shot 2016-03-04 at 16 38 39](https://cloud.githubusercontent.com/assets/425397/13531761/8649391e-e228-11e5-877c-9df0a4e042c4.png)

![screen shot 2016-03-04 at 16 38 48](https://cloud.githubusercontent.com/assets/425397/13531765/8de9ee52-e228-11e5-8bcd-c2fab8884dc0.png)

console:
```
myapp(46653,0x700000d5f000) malloc: *** error for object 0x7f8f4a5b54f0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

Sorry for "screenshooting" this issue :grimacing: , let me know if I can help in another way.

**Comment by adrianchifor** [comment] 2016-04-19 11:32
Happens to me as well. Got the same stacktrace as @nrako

**Comment by marmelroy** [comment] 2016-04-19 11:41
Thanks @adrianchifor. Do you have reproducible steps / code I can look at? It will be super useful...

**Comment by adrianchifor** [comment] 2016-04-19 12:39
This is where it crashes:

![screen shot 2016-04-19 at 13 36 27](https://cloud.githubusercontent.com/assets/6370064/14639309/f1144c96-0633-11e6-8162-33aa5530db76.png)

![screen shot 2016-04-19 at 13 37 14](https://cloud.githubusercontent.com/assets/6370064/14639317/0029690a-0634-11e6-831f-69a2ee5da99b.png)

The stacktrace:

![screen shot 2016-04-19 at 13 37 35](https://cloud.githubusercontent.com/assets/6370064/14639322/0aefb592-0634-11e6-839b-5352dfbfa1fe.png)

**Comment by marmelroy** [comment] 2016-04-19 12:43
Thanks @adrianchifor. I'll investigate tonight.

**Comment by adrianchifor** [comment] 2016-04-19 16:33
@marmelroy Managed to solve this for my project. Turned out that the issue was being caused by passing a string to _PhoneNumber.init_ from a strings array which was passed by reference to my function. The strings array was modified on another thread which caused EXC_BAD_ACCESS because PhoneNumberKit was trying to use a string that was no longer there.

**Comment by AppleLatino** [comment] 2016-04-19 16:33
## Su ticket fue creado. ##


Ticket subject: Re: [marmelroy/PhoneNumberKit] parseMultiple EXC_BAD_ACCESS (#29)


----
Autor: Adrian Chifor 
Fecha: Tue, 04/19/16 9:33 am
Mensaje:
@marmelroy Managed to solve this for my project. Turned out that the issue was being caused by passing a string to _PhoneNumber.init_ from a strings array which was passed by reference to my function. The strings array was modified on another thread which caused EXC_BAD_ACCESS because PhoneNumberKit was trying to use a string that was no longer there.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/marmelroy/PhoneNumberKit/issues/29#issuecomment-212007878



Powered by http://www.livechatinc.com

**Comment by AppleLatino** [comment] 2016-04-19 16:33
## Nuevo mensaje ##


Ticket subject: Re: [marmelroy/PhoneNumberKit] parseMultiple EXC_BAD_ACCESS (#29)


----
Autor:  AppleLatino 
Fecha: Tue, 04/19/16 9:33 am
Mensaje:
Thank you for contact me. I will reply your email as soon as possible. 

Gracias por contactarme. Le responderï¿½ lo mas pronto posible.


----
Autor: Adrian Chifor 
Fecha: Tue, 04/19/16 9:33 am
Mensaje:
@marmelroy Managed to solve this for my project. Turned out that the issue was being caused by passing a string to _PhoneNumber.init_ from a strings array which was passed by reference to my function. The strings array was modified on another thread which caused EXC_BAD_ACCESS because PhoneNumberKit was trying to use a string that was no longer there.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/marmelroy/PhoneNumberKit/issues/29#issuecomment-212007878



Powered by http://www.livechatinc.com

**Comment by marmelroy** [comment] 2016-04-19 16:44
Oh, okay. In that case I have a cool generalised solution in mind. Will commit in a few hours.

**Comment by AppleLatino** [comment] 2016-04-19 16:45
## Su ticket fue creado. ##


Ticket subject: Re: [marmelroy/PhoneNumberKit] parseMultiple EXC_BAD_ACCESS (#29)


----
Autor: Roy Marmelstein 
Fecha: Tue, 04/19/16 9:45 am
Mensaje:
Oh, okay. In that case I have a cool generalised solution in mind. Will commit in a few hours. 

---
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/marmelroy/PhoneNumberKit/issues/29#issuecomment-212011051



Powered by http://www.livechatinc.com

**Comment by marmelroy** [comment] 2016-04-19 23:08
Discovered a few possible issues here. Have a fix that I want to test more before pushing.

**Comment by AppleLatino** [comment] 2016-04-19 23:09
## Su ticket fue creado. ##


Ticket subject: Re: [marmelroy/PhoneNumberKit] parseMultiple EXC_BAD_ACCESS (#29)


----
Autor: Roy Marmelstein 
Fecha: Tue, 04/19/16 4:09 pm
Mensaje:
Discovered a few possible issues here. Have a fix that I want to test more before pushing. 

---
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/marmelroy/PhoneNumberKit/issues/29#issuecomment-212163356



Powered by http://www.livechatinc.com

**Comment by marmelroy** [comment] 2016-04-29 19:52
Should be fixed by https://github.com/marmelroy/PhoneNumberKit/commit/40410c875899bc3631a65d55826be2473c32af2a (new release soon).

**Closed by marmelroy** 2016-04-29 19:52 UTC
Labels: bug

**Comment by Jean-Daniel** [comment] 2018-12-12 22:41
This crash is due to concurrent access to the regularExpresionPool in RegexManager.
