### ISSUE TITLE
PhoneNumberParser: 'range(at:)' has been renamed to 'rangeAt(_:)'

### ISSUE THREAD

**Issue by seagullman** [marmelroy/PhoneNumberKit#187] opened 2017-12-01 17:16 UTC
I need to set a max number of digits on my PhoneNumberTextField via maxDigits. However, when I update PhoneNumberKit to 2.1, there is a compilation error in PhoneNumberParser on line 286:

 **'range(at:)' has been renamed to 'rangeAt(_:)'**

**Comment by bmwalters** [comment] 2017-12-15 23:17
Duplicate of #168. PhoneNumberKit is now a Swift 4 library, so to use the newest version you need to update your app to Swift 4. @seagullman

**Comment by williamtwilson** [comment] 2018-01-15 21:03
My app is using Swift 4 and I still see this error. Maybe it's a Cocoapods issue? I'll try to gather some more information.

**Comment by kuyazee** [comment] 2019-08-11 02:07
Closing this issue because we are now using Swift 5. See #263

**Closed by kuyazee** 2019-08-11 02:07 UTC
