### ISSUE TITLE
Not working in Simulator

### ISSUE THREAD

**Issue by tecexpert** [marmelroy/PhoneNumberKit#59] opened 2016-07-30 07:08 UTC
When I type "+" followed by "9", the "+" sign disappears.
So instead of "+9" , it only shows "9".

It is working fine on my iPhone 5s, iOS 9.3.3 though.

Xcode Version: 7.3

**Comment by marmelroy** [comment] 2016-08-06 10:53
Hi @tecexpert, I'm afraid I can't replicate. Can you please share more details?

**Comment by marmelroy** [comment] 2016-08-27 09:30
Closing due to lack of reproducible steps.

**Closed by marmelroy** 2016-08-27 09:30 UTC
